# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'manualcontrol.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(820, 550)
        self.gridLayout_2 = QtWidgets.QGridLayout(Dialog)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.neutral_position_push_button = QtWidgets.QPushButton(Dialog)
        self.neutral_position_push_button.setMinimumSize(QtCore.QSize(0, 30))
        self.neutral_position_push_button.setObjectName("neutral_position_push_button")
        self.gridLayout.addWidget(self.neutral_position_push_button, 7, 0, 1, 3)
        self.servo1_location_label = QtWidgets.QLabel(Dialog)
        self.servo1_location_label.setAlignment(QtCore.Qt.AlignCenter)
        self.servo1_location_label.setObjectName("servo1_location_label")
        self.gridLayout.addWidget(self.servo1_location_label, 1, 2, 1, 1)
        self.servo2_location_label = QtWidgets.QLabel(Dialog)
        self.servo2_location_label.setAlignment(QtCore.Qt.AlignCenter)
        self.servo2_location_label.setObjectName("servo2_location_label")
        self.gridLayout.addWidget(self.servo2_location_label, 2, 2, 1, 1)
        self.servo3_label = QtWidgets.QLabel(Dialog)
        self.servo3_label.setMinimumSize(QtCore.QSize(200, 40))
        self.servo3_label.setObjectName("servo3_label")
        self.gridLayout.addWidget(self.servo3_label, 3, 0, 1, 1)
        self.servo5_location_label = QtWidgets.QLabel(Dialog)
        self.servo5_location_label.setAlignment(QtCore.Qt.AlignCenter)
        self.servo5_location_label.setObjectName("servo5_location_label")
        self.gridLayout.addWidget(self.servo5_location_label, 5, 2, 1, 1)
        self.servo6_location_label = QtWidgets.QLabel(Dialog)
        self.servo6_location_label.setAlignment(QtCore.Qt.AlignCenter)
        self.servo6_location_label.setObjectName("servo6_location_label")
        self.gridLayout.addWidget(self.servo6_location_label, 6, 2, 1, 1)
        self.servo4_location_label = QtWidgets.QLabel(Dialog)
        self.servo4_location_label.setAlignment(QtCore.Qt.AlignCenter)
        self.servo4_location_label.setObjectName("servo4_location_label")
        self.gridLayout.addWidget(self.servo4_location_label, 4, 2, 1, 1)
        self.servo2_label = QtWidgets.QLabel(Dialog)
        self.servo2_label.setMinimumSize(QtCore.QSize(200, 40))
        self.servo2_label.setObjectName("servo2_label")
        self.gridLayout.addWidget(self.servo2_label, 2, 0, 1, 1)
        self.speed_label = QtWidgets.QLabel(Dialog)
        self.speed_label.setObjectName("speed_label")
        self.gridLayout.addWidget(self.speed_label, 0, 0, 1, 1)
        self.servo3_location_label = QtWidgets.QLabel(Dialog)
        self.servo3_location_label.setAlignment(QtCore.Qt.AlignCenter)
        self.servo3_location_label.setObjectName("servo3_location_label")
        self.gridLayout.addWidget(self.servo3_location_label, 3, 2, 1, 1)
        self.servo1_label = QtWidgets.QLabel(Dialog)
        self.servo1_label.setMinimumSize(QtCore.QSize(200, 40))
        self.servo1_label.setObjectName("servo1_label")
        self.gridLayout.addWidget(self.servo1_label, 1, 0, 1, 1)
        self.location_label = QtWidgets.QLabel(Dialog)
        self.location_label.setAlignment(QtCore.Qt.AlignCenter)
        self.location_label.setObjectName("location_label")
        self.gridLayout.addWidget(self.location_label, 0, 2, 1, 1)
        self.servo5_label = QtWidgets.QLabel(Dialog)
        self.servo5_label.setMinimumSize(QtCore.QSize(200, 40))
        self.servo5_label.setObjectName("servo5_label")
        self.gridLayout.addWidget(self.servo5_label, 5, 0, 1, 1)
        self.speed_spin_box = QtWidgets.QSpinBox(Dialog)
        self.speed_spin_box.setObjectName("speed_spin_box")
        self.gridLayout.addWidget(self.speed_spin_box, 0, 1, 1, 1)
        self.servo6_label = QtWidgets.QLabel(Dialog)
        self.servo6_label.setMinimumSize(QtCore.QSize(200, 40))
        self.servo6_label.setObjectName("servo6_label")
        self.gridLayout.addWidget(self.servo6_label, 6, 0, 1, 1)
        self.servo5_horizontal_slider = QtWidgets.QSlider(Dialog)
        self.servo5_horizontal_slider.setMaximumSize(QtCore.QSize(400, 16777215))
        self.servo5_horizontal_slider.setOrientation(QtCore.Qt.Horizontal)
        self.servo5_horizontal_slider.setObjectName("servo5_horizontal_slider")
        self.gridLayout.addWidget(self.servo5_horizontal_slider, 5, 1, 1, 1)
        self.servo4_label = QtWidgets.QLabel(Dialog)
        self.servo4_label.setMinimumSize(QtCore.QSize(200, 40))
        self.servo4_label.setObjectName("servo4_label")
        self.gridLayout.addWidget(self.servo4_label, 4, 0, 1, 1)
        self.servo1_horizontal_slider = QtWidgets.QSlider(Dialog)
        self.servo1_horizontal_slider.setMaximumSize(QtCore.QSize(400, 16777215))
        self.servo1_horizontal_slider.setOrientation(QtCore.Qt.Horizontal)
        self.servo1_horizontal_slider.setObjectName("servo1_horizontal_slider")
        self.gridLayout.addWidget(self.servo1_horizontal_slider, 1, 1, 1, 1)
        self.return_push_button = QtWidgets.QPushButton(Dialog)
        self.return_push_button.setMinimumSize(QtCore.QSize(0, 30))
        self.return_push_button.setObjectName("return_push_button")
        self.gridLayout.addWidget(self.return_push_button, 8, 0, 1, 3)
        self.servo2_horizontal_slider = QtWidgets.QSlider(Dialog)
        self.servo2_horizontal_slider.setMaximumSize(QtCore.QSize(400, 16777215))
        self.servo2_horizontal_slider.setOrientation(QtCore.Qt.Horizontal)
        self.servo2_horizontal_slider.setObjectName("servo2_horizontal_slider")
        self.gridLayout.addWidget(self.servo2_horizontal_slider, 2, 1, 1, 1)
        self.servo3_horizontal_slider = QtWidgets.QSlider(Dialog)
        self.servo3_horizontal_slider.setMaximumSize(QtCore.QSize(400, 16777215))
        self.servo3_horizontal_slider.setOrientation(QtCore.Qt.Horizontal)
        self.servo3_horizontal_slider.setObjectName("servo3_horizontal_slider")
        self.gridLayout.addWidget(self.servo3_horizontal_slider, 3, 1, 1, 1)
        self.servo4_horizontal_slider = QtWidgets.QSlider(Dialog)
        self.servo4_horizontal_slider.setMaximumSize(QtCore.QSize(400, 16777215))
        self.servo4_horizontal_slider.setOrientation(QtCore.Qt.Horizontal)
        self.servo4_horizontal_slider.setObjectName("servo4_horizontal_slider")
        self.gridLayout.addWidget(self.servo4_horizontal_slider, 4, 1, 1, 1)
        self.servo6_horizontal_slider = QtWidgets.QSlider(Dialog)
        self.servo6_horizontal_slider.setMaximumSize(QtCore.QSize(400, 16777215))
        self.servo6_horizontal_slider.setOrientation(QtCore.Qt.Horizontal)
        self.servo6_horizontal_slider.setObjectName("servo6_horizontal_slider")
        self.gridLayout.addWidget(self.servo6_horizontal_slider, 6, 1, 1, 1)
        self.commands_list_widget = QtWidgets.QListWidget(Dialog)
        self.commands_list_widget.setEnabled(True)
        self.commands_list_widget.setMinimumSize(QtCore.QSize(800, 150))
        self.commands_list_widget.setMaximumSize(QtCore.QSize(16777215, 150))
        self.commands_list_widget.setObjectName("commands_list_widget")
        self.gridLayout.addWidget(self.commands_list_widget, 9, 0, 1, 3)
        self.gridLayout_2.addLayout(self.gridLayout, 0, 0, 1, 1)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Kontrola manualna"))
        self.neutral_position_push_button.setText(_translate("Dialog", "Położenie neutralne"))
        self.servo1_location_label.setText(_translate("Dialog", "5/1000"))
        self.servo2_location_label.setText(_translate("Dialog", "500/1000"))
        self.servo3_label.setText(_translate("Dialog", "Serwo 3"))
        self.servo5_location_label.setText(_translate("Dialog", "134/1000"))
        self.servo6_location_label.setText(_translate("Dialog", "435/1000"))
        self.servo4_location_label.setText(_translate("Dialog", "400/100"))
        self.servo2_label.setText(_translate("Dialog", "Serwo 2"))
        self.speed_label.setText(_translate("Dialog", "Prędkość przestawiania"))
        self.servo3_location_label.setText(_translate("Dialog", "354/1000"))
        self.servo1_label.setText(_translate("Dialog", "Serwo 1"))
        self.location_label.setText(_translate("Dialog", "Położenie"))
        self.servo5_label.setText(_translate("Dialog", "Serwo 5"))
        self.servo6_label.setText(_translate("Dialog", "Serwo 6"))
        self.servo4_label.setText(_translate("Dialog", "Serwo 4"))
        self.return_push_button.setText(_translate("Dialog", "Powrót"))

