# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'manualcontrol.ui'
#
# Created by: PyQt5 UI code generator 5.11.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(820, 550)
        self.gridLayout_2 = QtWidgets.QGridLayout(Dialog)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.neutralPositionPushButton = QtWidgets.QPushButton(Dialog)
        self.neutralPositionPushButton.setMinimumSize(QtCore.QSize(0, 30))
        self.neutralPositionPushButton.setObjectName("neutralPositionPushButton")
        self.gridLayout.addWidget(self.neutralPositionPushButton, 7, 0, 1, 3)
        self.servo1LocationLabel = QtWidgets.QLabel(Dialog)
        self.servo1LocationLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.servo1LocationLabel.setObjectName("servo1LocationLabel")
        self.gridLayout.addWidget(self.servo1LocationLabel, 1, 2, 1, 1)
        self.servo2LocationLabel = QtWidgets.QLabel(Dialog)
        self.servo2LocationLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.servo2LocationLabel.setObjectName("servo2LocationLabel")
        self.gridLayout.addWidget(self.servo2LocationLabel, 2, 2, 1, 1)
        self.servo3Label = QtWidgets.QLabel(Dialog)
        self.servo3Label.setMinimumSize(QtCore.QSize(200, 40))
        self.servo3Label.setObjectName("servo3Label")
        self.gridLayout.addWidget(self.servo3Label, 3, 0, 1, 1)
        self.servo5LocationLabel = QtWidgets.QLabel(Dialog)
        self.servo5LocationLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.servo5LocationLabel.setObjectName("servo5LocationLabel")
        self.gridLayout.addWidget(self.servo5LocationLabel, 5, 2, 1, 1)
        self.servo6LocationLabel = QtWidgets.QLabel(Dialog)
        self.servo6LocationLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.servo6LocationLabel.setObjectName("servo6LocationLabel")
        self.gridLayout.addWidget(self.servo6LocationLabel, 6, 2, 1, 1)
        self.servo4LocationLabel = QtWidgets.QLabel(Dialog)
        self.servo4LocationLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.servo4LocationLabel.setObjectName("servo4LocationLabel")
        self.gridLayout.addWidget(self.servo4LocationLabel, 4, 2, 1, 1)
        self.servo2Label = QtWidgets.QLabel(Dialog)
        self.servo2Label.setMinimumSize(QtCore.QSize(200, 40))
        self.servo2Label.setObjectName("servo2Label")
        self.gridLayout.addWidget(self.servo2Label, 2, 0, 1, 1)
        self.speedLabel = QtWidgets.QLabel(Dialog)
        self.speedLabel.setObjectName("speedLabel")
        self.gridLayout.addWidget(self.speedLabel, 0, 0, 1, 1)
        self.servo3LocationLabel = QtWidgets.QLabel(Dialog)
        self.servo3LocationLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.servo3LocationLabel.setObjectName("servo3LocationLabel")
        self.gridLayout.addWidget(self.servo3LocationLabel, 3, 2, 1, 1)
        self.servo1Label = QtWidgets.QLabel(Dialog)
        self.servo1Label.setMinimumSize(QtCore.QSize(200, 40))
        self.servo1Label.setObjectName("servo1Label")
        self.gridLayout.addWidget(self.servo1Label, 1, 0, 1, 1)
        self.locationLabel = QtWidgets.QLabel(Dialog)
        self.locationLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.locationLabel.setObjectName("locationLabel")
        self.gridLayout.addWidget(self.locationLabel, 0, 2, 1, 1)
        self.servo5Label = QtWidgets.QLabel(Dialog)
        self.servo5Label.setMinimumSize(QtCore.QSize(200, 40))
        self.servo5Label.setObjectName("servo5Label")
        self.gridLayout.addWidget(self.servo5Label, 5, 0, 1, 1)
        self.speedSpinBox = QtWidgets.QSpinBox(Dialog)
        self.speedSpinBox.setObjectName("speedSpinBox")
        self.gridLayout.addWidget(self.speedSpinBox, 0, 1, 1, 1)
        self.servo6Label = QtWidgets.QLabel(Dialog)
        self.servo6Label.setMinimumSize(QtCore.QSize(200, 40))
        self.servo6Label.setObjectName("servo6Label")
        self.gridLayout.addWidget(self.servo6Label, 6, 0, 1, 1)
        self.servo5HorizontalSlider = QtWidgets.QSlider(Dialog)
        self.servo5HorizontalSlider.setMaximumSize(QtCore.QSize(400, 16777215))
        self.servo5HorizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.servo5HorizontalSlider.setObjectName("servo5HorizontalSlider")
        self.gridLayout.addWidget(self.servo5HorizontalSlider, 5, 1, 1, 1)
        self.servo4Label = QtWidgets.QLabel(Dialog)
        self.servo4Label.setMinimumSize(QtCore.QSize(200, 40))
        self.servo4Label.setObjectName("servo4Label")
        self.gridLayout.addWidget(self.servo4Label, 4, 0, 1, 1)
        self.servo1HorizontalSlider = QtWidgets.QSlider(Dialog)
        self.servo1HorizontalSlider.setMaximumSize(QtCore.QSize(400, 16777215))
        self.servo1HorizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.servo1HorizontalSlider.setObjectName("servo1HorizontalSlider")
        self.gridLayout.addWidget(self.servo1HorizontalSlider, 1, 1, 1, 1)
        self.returnPushButton = QtWidgets.QPushButton(Dialog)
        self.returnPushButton.setMinimumSize(QtCore.QSize(0, 30))
        self.returnPushButton.setObjectName("returnPushButton")
        self.gridLayout.addWidget(self.returnPushButton, 8, 0, 1, 3)
        self.servo2HorizontalSlider = QtWidgets.QSlider(Dialog)
        self.servo2HorizontalSlider.setMaximumSize(QtCore.QSize(400, 16777215))
        self.servo2HorizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.servo2HorizontalSlider.setObjectName("servo2HorizontalSlider")
        self.gridLayout.addWidget(self.servo2HorizontalSlider, 2, 1, 1, 1)
        self.servo3HorizontalSlider = QtWidgets.QSlider(Dialog)
        self.servo3HorizontalSlider.setMaximumSize(QtCore.QSize(400, 16777215))
        self.servo3HorizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.servo3HorizontalSlider.setObjectName("servo3HorizontalSlider")
        self.gridLayout.addWidget(self.servo3HorizontalSlider, 3, 1, 1, 1)
        self.servo4HorizontalSlider = QtWidgets.QSlider(Dialog)
        self.servo4HorizontalSlider.setMaximumSize(QtCore.QSize(400, 16777215))
        self.servo4HorizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.servo4HorizontalSlider.setObjectName("servo4HorizontalSlider")
        self.gridLayout.addWidget(self.servo4HorizontalSlider, 4, 1, 1, 1)
        self.servo6HorizontalSlider = QtWidgets.QSlider(Dialog)
        self.servo6HorizontalSlider.setMaximumSize(QtCore.QSize(400, 16777215))
        self.servo6HorizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.servo6HorizontalSlider.setObjectName("servo6HorizontalSlider")
        self.gridLayout.addWidget(self.servo6HorizontalSlider, 6, 1, 1, 1)
        self.commandsListWidget = QtWidgets.QListWidget(Dialog)
        self.commandsListWidget.setEnabled(True)
        self.commandsListWidget.setMinimumSize(QtCore.QSize(800, 150))
        self.commandsListWidget.setMaximumSize(QtCore.QSize(16777215, 150))
        self.commandsListWidget.setObjectName("commandsListWidget")
        self.gridLayout.addWidget(self.commandsListWidget, 9, 0, 1, 3)
        self.gridLayout_2.addLayout(self.gridLayout, 0, 0, 1, 1)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Kontrola manualna"))
        self.neutralPositionPushButton.setText(_translate("Dialog", "Położenie neutralne"))
        self.servo1LocationLabel.setText(_translate("Dialog", "5/1000"))
        self.servo2LocationLabel.setText(_translate("Dialog", "500/1000"))
        self.servo3Label.setText(_translate("Dialog", "Serwo 3"))
        self.servo5LocationLabel.setText(_translate("Dialog", "134/1000"))
        self.servo6LocationLabel.setText(_translate("Dialog", "435/1000"))
        self.servo4LocationLabel.setText(_translate("Dialog", "400/100"))
        self.servo2Label.setText(_translate("Dialog", "Serwo 2"))
        self.speedLabel.setText(_translate("Dialog", "Prędkość przestawiania"))
        self.servo3LocationLabel.setText(_translate("Dialog", "354/1000"))
        self.servo1Label.setText(_translate("Dialog", "Serwo 1"))
        self.locationLabel.setText(_translate("Dialog", "Położenie"))
        self.servo5Label.setText(_translate("Dialog", "Serwo 5"))
        self.servo6Label.setText(_translate("Dialog", "Serwo 6"))
        self.servo4Label.setText(_translate("Dialog", "Serwo 4"))
        self.returnPushButton.setText(_translate("Dialog", "Powrót"))

